"""
A타입 단위테스트 시나리오 xlsx 생성기.
4개 백엔드 서비스(auth/activity/documents/master)의 service 레이어 비즈니스 로직을 기반으로
실제 코드와 정확히 일치하는 단위테스트 케이스 시나리오를 작성한다.
"""
import openpyxl
from openpyxl.styles import Alignment, Font, PatternFill, Border, Side
from pathlib import Path

OUT = Path(__file__).parent

HEADER = ["테스트 케이스 ID", "기능", "테스트 조건", "입력 값", "기대 결과"]


HEADER_FILL = PatternFill("solid", fgColor="305496")
HEADER_FONT = Font(bold=True, color="FFFFFF")
BORDER = Border(
    left=Side(style="thin", color="999999"),
    right=Side(style="thin", color="999999"),
    top=Side(style="thin", color="999999"),
    bottom=Side(style="thin", color="999999"),
)
ALIGN = Alignment(wrap_text=True, vertical="top", horizontal="left")


def add_sheet(wb, sheet_title: str, rows: list[list[str]]):
    ws = wb.create_sheet(title=sheet_title)
    ws.append(HEADER)
    for cell in ws[1]:
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = Alignment(horizontal="center", vertical="center")
        cell.border = BORDER

    for row in rows:
        ws.append(row)

    for r in ws.iter_rows(min_row=2, max_row=ws.max_row):
        for cell in r:
            cell.alignment = ALIGN
            cell.border = BORDER

    widths = [16, 32, 50, 45, 55]
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[openpyxl.utils.get_column_letter(i)].width = w

    for row_idx in range(2, ws.max_row + 1):
        ws.row_dimensions[row_idx].height = 45

    print(f"sheet: {sheet_title} ({len(rows)} cases)")


# ============================================================
# 1. AUTH 서비스 단위테스트 시나리오
# ============================================================
auth_rows = [
    # AuthService.login
    ["TC-001", "로그인 성공",
     "ACTIVE 상태의 등록된 사용자가 정확한 이메일과 비밀번호로 로그인 시도",
     "email: user@team2.com, password: Pass1234! (DB의 BCrypt 해시와 매칭)",
     "TokenResponse 반환(accessToken, refreshToken, UserInfo 포함), refresh_tokens 테이블에 신규 토큰 1건 저장"],
    ["TC-002", "로그인 실패 - 존재하지 않는 이메일",
     "DB에 존재하지 않는 이메일로 AuthService.login 호출",
     "email: notfound@team2.com, password: any",
     "IllegalArgumentException(\"사용자를 찾을 수 없습니다.\") 발생"],
    ["TC-003", "로그인 실패 - 비밀번호 불일치",
     "존재하는 사용자에 대해 잘못된 비밀번호로 호출",
     "email: user@team2.com, password: wrongpw",
     "IllegalArgumentException(\"비밀번호가 일치하지 않습니다.\") 발생"],
    ["TC-004", "로그인 실패 - 비활성 상태(ON_LEAVE/RETIRED)",
     "userStatus가 ACTIVE가 아닌 사용자가 로그인 시도(canLogin()=false)",
     "email: leave@team2.com (status=ON_LEAVE), password: 정상",
     "IllegalStateException(\"로그인할 수 없는 상태입니다.\") 발생"],
    # AuthService.refreshToken
    ["TC-005", "리프레시 토큰 갱신 성공",
     "DB에 저장된 만료되지 않은 refresh token 값으로 refreshToken() 호출",
     "token: 유효한 UUID 토큰",
     "기존 refresh token 삭제, 새 access/refresh token 발급, TokenResponse 반환"],
    ["TC-006", "리프레시 토큰 갱신 실패 - 미존재 토큰",
     "RefreshTokenQueryMapper.findByTokenValue가 null 반환",
     "token: 임의의 문자열",
     "IllegalArgumentException(\"유효하지 않은 리프레시 토큰입니다.\") 발생"],
    ["TC-007", "리프레시 토큰 갱신 실패 - 만료 토큰",
     "tokenExpiresAt이 현재 시각보다 과거인 RefreshToken 조회",
     "token: 만료된 토큰",
     "해당 토큰 삭제 후 IllegalStateException(\"만료된 리프레시 토큰입니다.\") 발생"],
    # AuthService.logout
    ["TC-008", "로그아웃 성공",
     "userId 기준으로 사용자 조회 후 RefreshTokenRepository.deleteByUser 호출",
     "userId: 1",
     "해당 사용자의 모든 refresh token 삭제, void 반환"],
    ["TC-009", "로그아웃 실패 - 미존재 사용자",
     "userRepository.findById가 빈 Optional 반환",
     "userId: 99999",
     "IllegalArgumentException(\"사용자를 찾을 수 없습니다.\") 발생"],
    # UserCommandService.createUser
    ["TC-010", "사용자 생성 성공 (사번 자동 생성)",
     "이메일 중복이 없을 때 createUser 호출, 당일 사번 시퀀스에 따라 employeeNo 발급",
     "name: 홍길동, email: new@team2.com, password: Pass1234!, role: SALES",
     "User 저장, employeeNo는 yyMMdd + 2자리 시퀀스(예: 26040701), userStatus=ACTIVE, BCrypt 인코딩된 비밀번호 저장"],
    ["TC-011", "사용자 생성 실패 - 이메일 중복",
     "userQueryService.existsByUserEmail이 true 반환",
     "email: existing@team2.com",
     "IllegalArgumentException(\"이미 사용 중인 이메일입니다.\") 발생"],
    ["TC-012", "사용자 생성 실패 - 당일 사번 한도 초과",
     "당일 발급된 사번 시퀀스가 99에 도달한 상태에서 createUser 호출",
     "유효한 신규 사용자 정보",
     "IllegalStateException(\"당일 사번 발급 한도(99명)를 초과했습니다.\") 발생"],
    # UserCommandService.updateUser
    ["TC-013", "사용자 정보 수정 성공",
     "존재하는 사용자에 대해 이름/이메일/부서/직급 수정",
     "id: 1, name: 김갑돌, email: kim@team2.com, departmentId: 2, positionId: 3",
     "User.updateInfo 호출, assignDepartment·assignPosition 적용, 변경 감지로 DB 반영"],
    ["TC-014", "사용자 정보 수정 실패 - 미존재 부서",
     "departmentRepository.findById가 빈 Optional 반환",
     "id: 1, departmentId: 9999",
     "IllegalArgumentException(\"부서를 찾을 수 없습니다.\") 발생"],
    ["TC-015", "사용자 정보 수정 실패 - 미존재 직급",
     "positionRepository.findById가 빈 Optional 반환",
     "id: 1, positionId: 9999",
     "IllegalArgumentException(\"직급을 찾을 수 없습니다.\") 발생"],
    # UserCommandService.changePassword
    ["TC-016", "비밀번호 변경 성공",
     "현재 비밀번호가 일치하면 새 비밀번호를 BCrypt 인코딩 후 저장",
     "id: 1, currentPw: OldPass!, newPw: NewPass!",
     "user.userPw가 새 인코딩 값으로 변경됨"],
    ["TC-017", "비밀번호 변경 실패 - 현재 비밀번호 불일치",
     "passwordEncoder.matches가 false 반환",
     "id: 1, currentPw: wrong, newPw: any",
     "IllegalArgumentException(\"현재 비밀번호가 일치하지 않습니다.\") 발생"],
    # UserCommandService.resetPassword
    ["TC-018", "비밀번호 초기화 성공",
     "관리자에 의한 초기화 호출, 기본값 test1234로 인코딩 후 저장",
     "id: 1",
     "user.userPw가 BCrypt(\"test1234\")로 변경됨"],
    # UserCommandService.forgotPassword
    ["TC-019", "비밀번호 찾기 - 임시 비밀번호 메일 발송",
     "등록된 이메일로 forgotPassword 호출, 12자리 임시 비밀번호 생성",
     "email: user@team2.com",
     "임시 비밀번호로 user.userPw 갱신, EmailService.sendTemporaryPassword 호출"],
    ["TC-020", "비밀번호 찾기 실패 - 미등록 이메일",
     "userQueryService.getUserByEmail이 null 반환",
     "email: nobody@team2.com",
     "IllegalArgumentException(\"등록되지 않은 이메일입니다.\") 발생"],
    # UserCommandService.changeStatus + User entity
    ["TC-021", "사용자 상태 변경 성공",
     "ACTIVE → ON_LEAVE 등 정상 전이",
     "id: 1, status: ON_LEAVE",
     "user.userStatus = ON_LEAVE"],
    ["TC-022", "사용자 상태 변경 실패 - RETIRED 상태에서 변경 시도",
     "User.changeStatus 내부 검증: 퇴직자는 상태 변경 불가",
     "id: 1 (status=RETIRED), status: ACTIVE",
     "IllegalStateException(\"퇴직한 사용자의 상태는 변경할 수 없습니다.\") 발생"],
    # DepartmentCommandService
    ["TC-023", "부서 생성 성공",
     "DepartmentCommandService.createDepartment 호출",
     "name: 영업1팀",
     "Department 저장, 생성된 엔티티 반환"],
    ["TC-024", "부서 수정 성공",
     "존재하는 부서 ID에 대해 이름 변경",
     "id: 1, name: 해외영업팀",
     "department.departmentName이 변경됨"],
    ["TC-025", "부서 삭제 성공",
     "소속 사용자가 없는 부서 삭제",
     "id: 1 (소속 사용자 0명)",
     "DepartmentRepository.delete 호출"],
    ["TC-026", "부서 삭제 실패 - 소속 사용자 존재",
     "userQueryService.getUsersByDepartment가 비어있지 않음",
     "id: 1 (소속 사용자 5명)",
     "IllegalStateException(\"소속된 사용자가 있어 삭제할 수 없습니다.\") 발생"],
    # PositionCommandService
    ["TC-027", "직급 생성 성공",
     "PositionCommandService.createPosition 호출",
     "name: 부장, level: 1",
     "Position 저장, 생성된 엔티티 반환"],
    ["TC-028", "직급 수정 성공",
     "존재하는 직급 ID에 대해 name·level 변경",
     "id: 1, name: 차장, level: 2",
     "position.updateInfo 적용"],
    ["TC-029", "직급 삭제 성공",
     "PositionCommandService.deletePosition 호출",
     "id: 1",
     "PositionRepository.delete 호출"],
    # CompanyCommandService
    ["TC-030", "회사 정보 수정 성공",
     "단일 회사 row를 조회하여 updateInfo 호출",
     "UpdateCompanyRequest(name=Team2 Inc, ...)",
     "company.companyName 등 갱신, Company 반환"],
    ["TC-031", "회사 직인 이미지 업로드 성공",
     "S3FileService.upload(\"company/seal\", file) 호출 후 url을 sealImageUrl로 반영",
     "MultipartFile (PNG)",
     "S3 업로드 url 반환, company.companySealImageUrl 갱신"],
    # JwtProvider
    ["TC-032", "JWT Access 토큰 생성 및 검증",
     "JwtProvider.generateAccessToken 후 parseAccessToken으로 클레임 파싱",
     "User 엔티티",
     "Claims에 userId, email, role 등 포함, validateAccessToken=true"],
    ["TC-033", "JWT Access 토큰 검증 실패 - 잘못된 서명",
     "위변조된 토큰을 validateAccessToken에 전달",
     "임의 변형 토큰",
     "validateAccessToken 결과 false"],
]

# ============================================================
# 2. ACTIVITY 서비스 단위테스트 시나리오
# ============================================================
activity_rows = [
    # ActivityCommandService
    ["TC-001", "활동 생성 성공",
     "ActivityCommandService.createActivity 호출",
     "Activity 엔티티(clientId=1, activityType=MEETING, activityTitle=킥오프, activityDate=2026-04-07, authorId=10)",
     "activityRepository.save 호출, 저장된 Activity 반환"],
    ["TC-002", "활동 수정 성공",
     "존재하는 activityId에 대해 update 호출, authorId가 새 작성자로 갱신됨",
     "activityId: 1, request(타입/제목/내용/일정 등 변경), authorId: 20",
     "activity.update 적용, 변경 감지로 DB 반영"],
    ["TC-003", "활동 수정 실패 - 미존재",
     "activityRepository.findById가 빈 Optional 반환",
     "activityId: 9999",
     "IllegalArgumentException(\"활동을 찾을 수 없습니다.\") 발생"],
    ["TC-004", "활동 삭제 성공",
     "ActivityCommandService.deleteActivity 호출",
     "activityId: 1",
     "activityRepository.delete 호출"],
    ["TC-005", "활동 삭제 실패 - 미존재",
     "findById에서 빈 Optional 반환",
     "activityId: 9999",
     "IllegalArgumentException(\"활동을 찾을 수 없습니다.\") 발생"],
    # ActivityPackageCommandService
    ["TC-006", "활동 패키지 생성 성공",
     "ActivityPackageCommandService.createPackage 호출",
     "ActivityPackage(packageTitle=Q2 보고, creatorId=10)",
     "activityPackageRepository.save 호출, 저장된 ActivityPackage 반환"],
    ["TC-007", "활동 패키지 전체 수정 - viewer/item 교체",
     "viewerIds, activityIds가 모두 전달되어 기존 컬렉션을 clear 후 교체",
     "packageId: 1, request(viewerIds=[2,3,4], activityIds=[10,11])",
     "activityPackage.update 적용, viewers/items 컬렉션이 새 ID 목록으로 대체됨"],
    ["TC-008", "활동 패키지 부분 수정 - viewer/item 미전달",
     "viewerIds=null, activityIds=null인 경우 컬렉션 변경 없음",
     "packageId: 1, request(viewerIds=null, activityIds=null)",
     "기존 viewers/items 유지, 기본 정보(title/description/poId/dateFrom/dateTo)만 갱신"],
    ["TC-009", "활동 패키지 수정 실패 - 미존재",
     "findById에서 빈 Optional 반환",
     "packageId: 9999",
     "IllegalArgumentException(\"활동 패키지를 찾을 수 없습니다.\") 발생"],
    ["TC-010", "활동 패키지 삭제 성공",
     "ActivityPackageCommandService.deletePackage 호출",
     "packageId: 1",
     "activityPackageRepository.delete 호출"],
    # ContactCommandService
    ["TC-011", "연락처 생성 성공",
     "ContactCommandService.createContact 호출",
     "Contact(clientId=1, contactName=John, contactEmail=john@x.com)",
     "contactRepository.save 호출, 저장된 Contact 반환"],
    ["TC-012", "연락처 수정 성공",
     "존재하는 contactId에 대해 4개 필드 갱신",
     "contactId: 1, name=Jane, position=PM, email=jane@x.com, tel=+82-10-1111-2222",
     "contact.update 적용, 엔티티 반환"],
    ["TC-013", "연락처 수정 실패 - 미존재",
     "findById가 빈 Optional 반환",
     "contactId: 9999",
     "IllegalArgumentException(\"연락처를 찾을 수 없습니다.\") 발생"],
    ["TC-014", "연락처 삭제 성공",
     "ContactCommandService.deleteContact 호출",
     "contactId: 1",
     "contactRepository.delete 호출"],
    # EmailLogCommandService
    ["TC-015", "이메일 로그 저장 성공",
     "EmailLogCommandService.createEmailLog 호출",
     "EmailLog(clientId=1, emailRecipientEmail=a@x.com, emailStatus=PENDING)",
     "emailLogRepository.save 호출, 저장된 EmailLog 반환"],
    ["TC-016", "내부 이메일 로그 저장 성공",
     "documents 서비스에서 호출되는 createEmailLogInternal",
     "EmailLogInternalRequest",
     "request.toEntity() → repository.save"],
    ["TC-017", "이메일 재전송 성공",
     "FAILED 상태 로그를 documentsFeignClient.sendEmail로 재전송, response.status=SENT",
     "emailLogId: 1 (FAILED), userId: 10",
     "emailLog.markAsSent 호출, EmailLog 반환"],
    ["TC-018", "이메일 재전송 실패 - 이미 SENT",
     "emailStatus가 SENT인 로그에 대해 resend 호출",
     "emailLogId: 1 (SENT)",
     "IllegalStateException(\"이미 발송된 이메일입니다.\") 발생"],
    ["TC-019", "이메일 재전송 실패 - PENDING 상태",
     "아직 발송 시도 전 상태에서 resend 호출",
     "emailLogId: 1 (PENDING)",
     "IllegalStateException(\"아직 발송 시도 전인 이메일입니다.\") 발생"],
    ["TC-020", "이메일 재전송 실패 - documents 호출 예외",
     "Feign 호출에서 예외 발생, catch 후 markAsFailed",
     "emailLogId: 1 (FAILED), userId: 10, FeignException 발생",
     "emailLog.markAsFailed 호출, 이후 IllegalStateException(\"이메일 재전송에 실패했습니다.\") 발생"],
    ["TC-021", "이메일 재전송 실패 - response.status=FAILED",
     "Feign 응답이 FAILED일 때",
     "emailLogId: 1 (FAILED), response.status=\"FAILED\"",
     "markAsFailed 호출 후 IllegalStateException 발생"],
    ["TC-022", "이메일 로그 삭제 성공",
     "EmailLogCommandService.deleteEmailLog 호출",
     "emailLogId: 1",
     "emailLogRepository.delete 호출"],
    # ActivityQueryService
    ["TC-023", "활동 단건 조회 성공 + 외부 이름 보강",
     "MyBatis 매퍼 조회 후 AuthFeignClient/MasterFeignClient로 작성자명·거래처명 enrich",
     "activityId: 1",
     "ActivityResponse(authorName=홍길동, clientName=ABC상사) 반환"],
    ["TC-024", "활동 단건 조회 실패 - 미존재",
     "ActivityQueryMapper.findById가 null 반환",
     "activityId: 9999",
     "IllegalArgumentException(\"활동을 찾을 수 없습니다.\") 발생"],
    ["TC-025", "활동 필터 조회",
     "client/PO/type/author/dateRange/keyword/page/size 필터로 조회",
     "clientId=1, activityType=ISSUE, page=0, size=10",
     "List<ActivityResponse> 반환, enrichActivities 적용"],
    ["TC-026", "활동 날짜 범위 조회 - null 검증",
     "ActivityQueryService.getActivitiesByDateRange에서 null 입력",
     "from=null, to=null",
     "IllegalArgumentException(\"날짜 범위(from, to)는 필수입니다.\") 발생"],
    # ActivityPackageQueryService
    ["TC-027", "활동 패키지 단건 조회 실패 - 미존재",
     "ActivityPackageQueryMapper.findById가 null 반환",
     "packageId: 9999",
     "IllegalArgumentException(\"활동 패키지를 찾을 수 없습니다.\") 발생"],
    ["TC-028", "활동 패키지 viewer 기준 조회",
     "viewer userId 기준으로 + creatorId/poId 옵션 필터",
     "userId: 5, creatorId: null, poId: null",
     "List<ActivityPackageResponse> 반환, creator 이름 enrich"],
    # EmailLogQueryService
    ["TC-029", "이메일 로그 단건 조회 성공",
     "MyBatis 조회 후 sender/client 이름 enrich",
     "emailLogId: 1",
     "EmailLogResponse 반환"],
    ["TC-030", "이메일 로그 필터 조회",
     "clientId/poId/status/sender/keyword/dateRange/page/size 필터",
     "emailStatus=FAILED, page=0, size=20",
     "List<EmailLogResponse> 반환"],
    # PDF Report
    ["TC-031", "활동 패키지 PDF 보고서 생성",
     "ActivityPackagePdfReportService.generatePackageReport 호출, 한글 폰트 로드",
     "ActivityPackage, userId: 10",
     "byte[] PDF 반환, 표 내용에 패키지 활동 목록 포함"],
    ["TC-032", "활동 패키지 PDF 다운로드 파일명 생성",
     "패키지 제목에서 unsafe 문자 제거 후 .pdf 확장자 부여",
     "packageTitle=\"Q2/보고:최종\"",
     "Q2_보고_최종.pdf 형식 파일명 반환"],
]

# ============================================================
# 3. DOCUMENTS 서비스 단위테스트 시나리오
# ============================================================
documents_rows = [
    # PurchaseOrderCreationService
    ["TC-001", "PO 생성 성공 - 요청에 poId 미포함",
     "DocumentNumberGeneratorService.nextPurchaseOrderId 호출하여 신규 코드 발급",
     "PurchaseOrderCreateRequest(poId=null, items=[...])",
     "PO 저장, status=DRAFT, 자동 발급 poId(예: PO260001) 사용, 스냅샷 저장 및 CREATE 이력 기록"],
    ["TC-002", "PO 생성 - 요청 poId 사용",
     "request.poId가 비어있지 않으면 그대로 사용",
     "PurchaseOrderCreateRequest(poId=PO260123)",
     "발급 호출 없이 PO260123으로 저장"],
    ["TC-003", "PO 생성 - totalAmount 자동 계산",
     "request.totalAmount=null이면 items의 amount 합계로 계산",
     "items 2건 (각 amount=100, 200)",
     "totalAmount=300으로 저장"],
    ["TC-004", "PO 생성 - PI 연결 자동 호출",
     "request.piId가 비어있지 않으면 documentLinkService.linkPurchaseOrderToProformaInvoice 호출",
     "piId: PI260001",
     "linkPurchaseOrderToProformaInvoice 호출, 링크 생성"],
    ["TC-005", "PO 초기 상태는 항상 DRAFT",
     "determineInitialStatus(userId) 호출",
     "userId: 임의",
     "PurchaseOrderStatus.DRAFT 반환"],
    # PurchaseOrderRegistrationService
    ["TC-006", "PO 등록 요청 - 일반 사원",
     "PositionLevel이 MANAGER가 아닌 사용자가 DRAFT PO에 대해 등록 요청",
     "poId: PO260001 (DRAFT), userId: 10 (사원)",
     "status=APPROVAL_PENDING으로 변경, ApprovalRequest(REGISTRATION) 생성"],
    ["TC-007", "PO 등록 요청 - 관리자 즉시 확정",
     "PositionLevel.MANAGER 사용자가 DRAFT PO 등록 요청",
     "poId: PO260001 (DRAFT), userId: 99 (MANAGER)",
     "status=CONFIRMED, 자동 문서 생성 호출, 이력 기록"],
    ["TC-008", "PO 등록 요청 실패 - DRAFT 아님",
     "이미 APPROVAL_PENDING 등 상태인 PO에 대해 등록 요청",
     "poId: PO260001 (APPROVAL_PENDING)",
     "BusinessConflictException(\"초안 상태의 PO만 등록 요청할 수 있습니다.\") 발생"],
    ["TC-009", "PO 등록 요청 실패 - 사용자 직급 정보 없음",
     "userPositionRepository.findPositionLevelByUserId가 빈 Optional 반환",
     "poId: PO260001, userId: 미등록",
     "ResourceNotFoundException(\"사용자 직급 정보를 찾을 수 없습니다.\") 발생"],
    # PurchaseOrderApprovalService
    ["TC-010", "PO 승인 성공",
     "APPROVAL_PENDING 상태의 PO를 CONFIRMED로 전환, 자동 문서 생성 호출",
     "poId: PO260001 (APPROVAL_PENDING)",
     "status=CONFIRMED, generateOnConfirmation 호출"],
    ["TC-011", "PO 승인 실패 - 결재대기 아님",
     "DRAFT 또는 CONFIRMED 상태에서 approve 호출",
     "poId: PO260001 (DRAFT)",
     "IllegalStateException(\"결재대기 상태의 PO만 승인할 수 있습니다.\") 발생"],
    # PurchaseOrderRejectionService
    ["TC-012", "PO 반려 성공",
     "APPROVAL_PENDING 상태의 PO를 REJECTED로 전환",
     "poId: PO260001 (APPROVAL_PENDING)",
     "status=REJECTED 저장"],
    ["TC-013", "PO 반려 실패 - 결재대기 아님",
     "DRAFT 상태에서 reject 호출",
     "poId: PO260001 (DRAFT)",
     "IllegalStateException(\"결재대기 상태의 PO만 반려할 수 있습니다.\") 발생"],
    # PurchaseOrderApprovalWorkflowService
    ["TC-014", "PO 결재 워크플로우 - 승인 위임",
     "ApprovalRequestCommandService.updatePendingDocument(PO, poId, APPROVED) 호출",
     "poId: PO260001",
     "결재 요청 상태가 APPROVED로 갱신되며 문서 워크플로우 트리거"],
    # PurchaseOrderModificationService
    ["TC-015", "PO 수정 가능 검증 - 정상",
     "출하 상태가 COMPLETED가 아닐 때 validateModifiable 호출",
     "poId: PO260001 (shipment=PENDING)",
     "예외 없이 통과"],
    ["TC-016", "PO 수정 불가 - 출하완료",
     "ShipmentStatus.COMPLETED인 PO 수정 시도",
     "poId: PO260001 (shipment=COMPLETED)",
     "IllegalStateException(\"출하완료 상태의 PO는 수정할 수 없습니다.\") 발생"],
    ["TC-017", "PO 삭제 불가 - 출하완료",
     "ShipmentStatus.COMPLETED인 PO 삭제 검증",
     "poId: PO260001 (shipment=COMPLETED)",
     "IllegalStateException(\"출하완료 상태의 PO는 삭제할 수 없습니다.\") 발생"],
    # ApprovalRequestCommandService
    ["TC-018", "결재 요청 생성 성공",
     "ApprovalRequestCommandService.create 호출",
     "ApprovalRequestCreateRequest(documentType=PO, documentId=PO260001, requesterId=10, approverId=1)",
     "ApprovalRequest 저장, markRequested 및 이력 기록"],
    ["TC-019", "결재 요청 - APPROVED 처리",
     "update(id, APPROVED) 호출",
     "approvalRequestId: 1, status=APPROVED",
     "approveDocument 호출, status=APPROVED, reviewedAt 기록"],
    ["TC-020", "결재 요청 - REJECTED 처리",
     "update(id, REJECTED, comment) 호출",
     "approvalRequestId: 1, status=REJECTED, comment=반려사유",
     "rejectDocument 호출, status=REJECTED, reviewSnapshot=comment"],
    ["TC-021", "결재 요청 처리 실패 - 잘못된 status",
     "PENDING 등 처리 불가 상태로 update 호출",
     "approvalRequestId: 1, status=PENDING",
     "IllegalArgumentException(\"승인 또는 반려 상태만 처리할 수 있습니다.\") 발생"],
    ["TC-022", "결재 요청 조회 실패 - 미존재",
     "approvalRequestRepository.findById가 빈 Optional 반환",
     "approvalRequestId: 9999",
     "IllegalArgumentException(\"결재 요청 정보를 찾을 수 없습니다.\") 발생"],
    # CollectionCommandService
    ["TC-023", "수금 완료 처리 성공",
     "미수금 상태 collection을 수금완료로 변경",
     "collectionId: 1 (status=미수금), targetStatus=수금완료, date=2026-04-07",
     "collection.status=수금완료, collectionDate 저장"],
    ["TC-024", "수금 완료 실패 - targetStatus 검증",
     "수금완료 외 값 전달",
     "targetStatus=취소",
     "IllegalArgumentException(\"수금완료 상태만 처리할 수 있습니다.\") 발생"],
    ["TC-025", "수금 완료 실패 - 이미 수금완료",
     "collection.status가 미수금이 아닐 때",
     "collectionId: 1 (status=수금완료)",
     "IllegalStateException(\"미수금 상태의 현황만 수금완료 처리할 수 있습니다.\") 발생"],
    ["TC-026", "수금 조회 실패 - 미존재",
     "collectionRepository.findById가 빈 Optional 반환",
     "collectionId: 9999",
     "IllegalArgumentException(\"매출·수금 현황 정보를 찾을 수 없습니다.\") 발생"],
    # ShipmentCommandService
    ["TC-027", "출하 상태 변경 성공",
     "ShipmentCommandService.updateStatus 호출",
     "shipmentId: 1, status: COMPLETED",
     "shipment.shipmentStatus=COMPLETED 저장"],
    ["TC-028", "출하 조회 실패 - 미존재",
     "findById가 빈 Optional 반환",
     "shipmentId: 9999",
     "IllegalArgumentException(\"출하현황 정보를 찾을 수 없습니다.\") 발생"],
    ["TC-029", "PO 기준 출하 조회 실패 - 미존재",
     "findByPoCode가 빈 Optional 반환",
     "poId: PO_NOT_EXIST",
     "IllegalArgumentException(\"해당 PO의 출하현황 정보를 찾을 수 없습니다.\") 발생"],
    # DocumentNumberGeneratorService
    ["TC-030", "문서 번호 신규 시퀀스 생성",
     "해당 prefix가 DB에 없을 때 nextPurchaseOrderId 호출",
     "현재 연도: 2026",
     "PO26 prefix로 새 시퀀스 row 생성, 첫 번호 PO260001 반환"],
    ["TC-031", "문서 번호 증분",
     "기존 시퀀스 lastNumber=5에서 호출",
     "prefix: PO26",
     "lastNumber=6으로 증분 후 PO260006 반환"],
    ["TC-032", "PI/CI/PL/SO/MO 번호 발급",
     "각 prefix에 대해 next 호출",
     "-",
     "각각 PI26xxxx, CI26xxxx, PL26xxxx, SO26xxxx, MO26xxxx 형식 반환"],
    # ExchangeRateService
    ["TC-033", "환율 조회 - KRW 대상이면 1 반환",
     "targetCurrencyCode가 KRW일 때 외부 호출 없이 BigDecimal.ONE 반환",
     "issueDate=2026-04-07, targetCurrencyCode=KRW",
     "BigDecimal.ONE"],
    ["TC-034", "환율 조회 - 외부 API 호출",
     "KRW가 아닐 때 currencyApiClient.getRate 호출",
     "targetCurrencyCode=USD",
     "API에서 받은 rate 반환"],
    ["TC-035", "KRW → 외화 환산",
     "convertFromKrw 호출 시 rate 곱하고 소수점 2자리 HALF_UP",
     "issueDate=2026-04-07, target=USD, krwAmount=130000 (rate=0.000769)",
     "BigDecimal(\"99.97\") 등 (소수 2자리 반올림)"],
    ["TC-036", "KRW 환산 - null 입력",
     "krwAmount=null",
     "krwAmount=null",
     "BigDecimal.ZERO 반환"],
    ["TC-037", "통화 코드 정규화 - null/blank",
     "normalizeCurrencyCode 내부 분기",
     "currencyCode=null",
     "KRW로 정규화"],
]

# ============================================================
# 4. MASTER 서비스 단위테스트 시나리오
# ============================================================
master_rows = [
    # CurrencyCommandService
    ["TC-001", "통화 생성 성공",
     "통화 코드 중복이 없을 때 create 호출",
     "currencyCode=USD, currencyName=US Dollar, currencySymbol=$",
     "Currency 저장, 생성된 엔티티 반환"],
    ["TC-002", "통화 생성 실패 - 코드 중복",
     "existsByCurrencyCode가 true 반환",
     "currencyCode=USD (이미 존재)",
     "IllegalStateException(\"이미 존재하는 통화 코드입니다: USD\") 발생"],
    ["TC-003", "통화 수정 성공",
     "수정 대상 통화 조회 후 update",
     "id: 1, request(code=USD, name=달러, symbol=$)",
     "currency.update 적용"],
    ["TC-004", "통화 수정 실패 - 다른 ID에 동일 코드 존재",
     "동일 코드를 가진 다른 통화 row 존재",
     "id: 1, code=EUR (id=2가 이미 EUR 사용)",
     "IllegalStateException(\"이미 존재하는 통화 코드입니다: EUR\") 발생"],
    ["TC-005", "통화 수정 실패 - 미존재",
     "findById가 빈 Optional 반환",
     "id: 9999",
     "ResourceNotFoundException 발생"],
    ["TC-006", "통화 삭제 성공",
     "CurrencyCommandService.delete 호출",
     "id: 1",
     "currencyRepository.delete 호출"],
    # CountryCommandService (동일 패턴)
    ["TC-007", "국가 생성 성공",
     "코드 중복이 없을 때 create 호출",
     "countryCode=KR, countryName=Korea",
     "Country 저장"],
    ["TC-008", "국가 생성 실패 - 코드 중복",
     "existsByCountryCode true",
     "countryCode=KR",
     "IllegalStateException 발생"],
    ["TC-009", "국가 수정/삭제 - 미존재",
     "findById 빈 Optional",
     "id: 9999",
     "ResourceNotFoundException 발생"],
    # ClientCommandService
    ["TC-010", "거래처 생성 성공 - 모든 관계 포함",
     "코드 중복이 없을 때 country/port/paymentTerm/currency 모두 매핑하여 저장",
     "CreateClientRequest(clientCode=CL001, countryId=1, portId=1, paymentTermId=1, currencyId=1)",
     "Client 저장, clientStatus=ACTIVE, 4개 연관관계 모두 설정"],
    ["TC-011", "거래처 생성 실패 - 코드 중복",
     "existsByClientCode true",
     "clientCode=CL001",
     "IllegalStateException(\"이미 사용 중인 거래처 코드입니다.\") 발생"],
    ["TC-012", "거래처 생성 실패 - 미존재 국가",
     "countryRepository.findById 빈 Optional",
     "countryId: 9999",
     "ResourceNotFoundException(\"국가를 찾을 수 없습니다.\") 발생"],
    ["TC-013", "거래처 생성 실패 - 미존재 항구",
     "portRepository.findById 빈 Optional",
     "portId: 9999",
     "ResourceNotFoundException(\"항구를 찾을 수 없습니다.\") 발생"],
    ["TC-014", "거래처 생성 실패 - 미존재 결제조건",
     "paymentTermRepository.findById 빈 Optional",
     "paymentTermId: 9999",
     "ResourceNotFoundException(\"결제조건을 찾을 수 없습니다.\") 발생"],
    ["TC-015", "거래처 생성 실패 - 미존재 통화",
     "currencyRepository.findById 빈 Optional",
     "currencyId: 9999",
     "ResourceNotFoundException(\"통화를 찾을 수 없습니다.\") 발생"],
    ["TC-016", "거래처 생성 - 옵션 관계 미포함",
     "countryId/portId/paymentTermId/currencyId가 모두 null인 경우",
     "CreateClientRequest(필수만)",
     "Client 저장, 4개 연관관계는 null 유지"],
    ["TC-017", "거래처 수정 성공",
     "기존 클라이언트 조회 후 updateInfo + 관계 재할당",
     "id: 1, request(name=ABC corp, countryId=2, ...)",
     "client.updateInfo 호출, 새 country 등 할당"],
    ["TC-018", "거래처 수정 실패 - 미존재",
     "findByIdWithRelations 빈 Optional",
     "id: 9999",
     "ResourceNotFoundException(\"거래처를 찾을 수 없습니다.\") 발생"],
    ["TC-019", "거래처 상태 변경 성공",
     "ClientCommandService.changeStatus 호출",
     "id: 1, status: INACTIVE",
     "client.changeStatus 적용"],
    # BuyerCommandService
    ["TC-020", "바이어 생성 성공",
     "BuyerCommandService.createBuyer 호출 - clientId 검증 포함",
     "CreateBuyerRequest(clientId=1, name=John, position=PM)",
     "Buyer 저장, 연관 client 설정"],
    ["TC-021", "바이어 수정 성공",
     "존재하는 buyerId에 대해 4개 필드 갱신",
     "id: 1, name=Jane",
     "buyer.updateInfo 적용"],
    ["TC-022", "바이어 삭제 성공",
     "BuyerCommandService.deleteBuyer 호출",
     "id: 1",
     "buyerRepository.delete 호출"],
    # ItemCommandService
    ["TC-023", "품목 생성 성공",
     "품목 코드 중복이 없을 때 createItem 호출",
     "CreateItemRequest(itemCode=I001, itemName=Bolt, itemUnitPrice=100.00)",
     "Item 저장, itemStatus=ACTIVE"],
    ["TC-024", "품목 생성 실패 - 코드 중복",
     "existsByItemCode true",
     "itemCode=I001 (이미 존재)",
     "IllegalStateException(\"이미 사용 중인 품목 코드입니다.\") 발생"],
    ["TC-025", "품목 수정 성공",
     "9개 필드 일괄 갱신",
     "id: 1, request(name/spec/unit/price/weight 등)",
     "item.updateInfo 적용"],
    ["TC-026", "품목 수정 실패 - 미존재",
     "findById 빈 Optional",
     "id: 9999",
     "ResourceNotFoundException(\"품목을 찾을 수 없습니다.\") 발생"],
    ["TC-027", "품목 상태 변경 성공",
     "ACTIVE → INACTIVE 전이",
     "id: 1, status: INACTIVE",
     "item.changeStatus 적용"],
    # PortCommandService
    ["TC-028", "항구 생성 성공",
     "코드 중복 없음 + 국가 존재",
     "portCode=KRPUS, portName=Busan, countryId=1",
     "Port 저장, PortResponse 반환"],
    ["TC-029", "항구 생성 실패 - 코드 중복",
     "existsByPortCode true",
     "portCode=KRPUS",
     "IllegalStateException(\"이미 존재하는 항구 코드입니다: KRPUS\") 발생"],
    ["TC-030", "항구 생성 실패 - 미존재 국가",
     "countryRepository.findById 빈 Optional",
     "countryId: 9999",
     "ResourceNotFoundException 발생"],
    ["TC-031", "항구 수정 - 코드 변경 시 다른 ID 중복 검증",
     "findByPortCode 결과 ID가 본인이 아닐 때 충돌",
     "id: 1, portCode=KRPUS (id=2가 이미 사용)",
     "IllegalStateException(\"이미 존재하는 항구 코드입니다: KRPUS\") 발생"],
    ["TC-032", "항구 수정 성공 - 자기 코드 유지",
     "findByPortCode 결과가 자기 자신",
     "id: 1, portCode=KRPUS (자기 코드)",
     "검증 통과, port.update 적용"],
    ["TC-033", "항구 삭제 성공",
     "PortCommandService.delete 호출",
     "id: 1",
     "portRepository.delete 호출"],
    # PaymentTermCommandService
    ["TC-034", "결제조건 생성/수정/삭제",
     "코드 중복 검증 후 처리, 동일 패턴",
     "paymentTermCode=TT, name=T/T",
     "PaymentTerm 저장/수정/삭제"],
    # IncotermCommandService
    ["TC-035", "인코텀즈 생성 성공",
     "incotermCode 중복 검증 후 저장",
     "incotermCode=FOB, transportMode=Sea",
     "Incoterm 저장"],
    ["TC-036", "인코텀즈 생성 실패 - 코드 중복",
     "existsByIncotermCode true",
     "incotermCode=FOB",
     "IllegalStateException 발생"],
    # Query - pagination
    ["TC-037", "거래처 페이징 조회",
     "ClientQueryService.getClients(name, countryId, status, deptId, page, size)",
     "name=ABC, page=0, size=10",
     "PagedResponse<ClientListResponse>(content, totalElements, totalPages, currentPage)"],
    ["TC-038", "품목 페이징 조회",
     "ItemQueryService.getItems(name, category, status, page, size)",
     "category=Hardware, page=0, size=20",
     "PagedResponse<ItemListResponse> 반환"],
    # Entity behavior
    ["TC-039", "Client.changeStatus - ACTIVE/INACTIVE 전이",
     "엔티티 changeStatus 호출",
     "INACTIVE → ACTIVE",
     "clientStatus=ACTIVE 변경"],
    ["TC-040", "ClientStatus.fromDbValue - 매핑",
     "DB 문자열에서 enum 변환",
     "\"active\"",
     "ClientStatus.ACTIVE 반환"],
]

wb = openpyxl.Workbook()
wb.remove(wb.active)
add_sheet(wb, "Auth", auth_rows)
add_sheet(wb, "Activity", activity_rows)
add_sheet(wb, "Documents", documents_rows)
add_sheet(wb, "Master", master_rows)
wb.save(OUT / "단위_테스트_시나리오.xlsx")
print("done")
